bazbia/urls.py
from django.contrib import admin
from django.urls import path ,include
from shop import views 
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.list_product  , name = 'index' ),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('customer/', include('customer.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls'))

]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('reducenumber/<product_id>' , views.reduce_number_from_cart , name = 'reduce_number_from_cart'),
    path('list/', views.show_cart, name='show_cart'),
    path('codeTkhfif/',views.codeTakhfif , name='codeTakhfif'),
    path('deletTkhfif/',views.deletTakhfif , name='delet_takhfif'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(label='',
        min_value=1, max_value=9, widget=forms.NumberInput(
            attrs={'class': 'form-control mt-1','placeholder': 'quantity'}
        )
    )

cart/views.py
from customer.models import Takhfif

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from cart.utils.cart import Cart
from .forms import QuantityForm
from shop.models import Product


def add_to_cart(request, product_id):
    
    ###  اضافه کردن یک محصول به داخل سبد خرید 

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)   #  محصولی که می خواهیم به سبد خرید اضافه کنیم
    cart.add(product=product, quantity=1)          
    messages.success(request, 'Added to your cart!', 'info')
    return redirect('cart:show_cart')


     # to do لیست انبار باید چک شود 

def show_cart(request):
    cart = Cart(request)

    # چک کردن سبد خرید   
    if len(cart.cart) == 0 :
      messages.add_message(request, messages.INFO, "  سبد خرید خالی است   " , extra_tags="danger")
      return redirect ("/shop")
  
    hamlonaghl = 50000 
    codetakhfif = request.session.get("takhfif")
    try :
     takhfif = Takhfif.objects.get(code =  codetakhfif)
    except : 
       takhfif = None 

    # بررسی  میزان تخفیف فاکتور 
    # محدودیت تخفیف با فیلد maximum
    # اگر برابر با  -1 باشد تخفیف نا محدود است 

    jamekol = cart.get_total_price()
    if (takhfif):
      mtakhfif = int(jamekol * takhfif.darsad) 
      if takhfif.maximum != -1 : 
       if(mtakhfif > takhfif.maximum): 
        mtakhfif = takhfif.maximum
    else :
      mtakhfif = 0 

    kol = jamekol + hamlonaghl - mtakhfif 
  

    print(cart)
    context = {
        'cart': cart ,                                  #   لیست محصولات 
        'alljame': jamekol,                             #   جمع قیمت یدون محاسبه تخفیف
        'hamlonaghl' : hamlonaghl,                      #   هزینه حمل ونقل 
        'kol': kol,                                     #   جمع قیمت با محاسبه تخفیف 
        'takhfif' : mtakhfif,                           #   میزان تخفیف 
          
          
          
               }

    return render(request, 'cart/list_sabad.html', context)


@login_required
def remove_from_cart(request, product_id):
    
    ########## برای حذف یک محصول از داخل سبد خرید 

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:show_cart')


def reduce_number_from_cart(request , product_id): 
    cart = Cart(request)
    product = get_object_or_404(Product , id=product_id)
    cart.reduceNumber(product)
    messages.success(request, 'remove  from your cart!', 'info')

    return redirect('cart:show_cart')



# بررسی کد تخفیف 
def codeTakhfif(request): 
    
   code = request.POST['code']
   try:  
         takhfif =  Takhfif.objects.get(code = code) 
         if(takhfif) : 
          request.session['takhfif'] = takhfif.code
          messages.add_message(request, messages.INFO,  "  کد تخفیف  " + takhfif.name +  "  اعمال شد     "  , extra_tags= 'success')
         else : 
              messages.add_message(request, messages.INFO, " کد تخیف موجود نیست  " , extra_tags='warning')
   except: 
     messages.add_message(request, messages.INFO, " کد تخیف موجود نیست  " , extra_tags='warning') 





   return redirect('cart:show_cart')   

# حذف کد تخفیف
def deletTakhfif(request): 
       
   del request.session['takhfif']
   messages.add_message(request, messages.INFO, " کد تخفیف حذف شد     " , extra_tags='danger')
   return redirect('cart:show_cart')   

cart/templates/cart/cart.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-2"></div>
{% if cart_count != 0 %}
<div class="col-md-8 border rounded p-3">
<table class="table table-striped ">
    <thead class="text-muted">
      <tr>
        <th scope="col"></th>
        <th scope="col">product</th>
        <th scope="col">price</th>
        <th scope="col">quantity</th>
        <th scope="col">total price</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for item in cart %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a></td>
        <td>${{ item.price }}</td>
        <td>{{ item.quantity }}</td>
        <td>${{ item.total_price }}</td>
        <td><a class="text-danger text-decoration-none" href="{% url 'cart:remove_from_cart' item.product.id %}">remove</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>
<hr>
<a href="{% url 'orders:create_order' %}" style="float: right;" class="btn btn-success mt-1">Checkout</a>
<h4 class="mt-4"><span class="text-muted">Total:</span> ${{ cart.get_total_price }}</h4>
</div>
{% else %}
<div class="col-md-8 mt-5 pt-5 text-center">
  <br>
  <h3 class="text-muted text-capitalize">cart is empty..!</h3>
  <a href="/" class="text-primary text-decoration-none">Back</a>
</div>
{% endif %}
<div class="col-md-2"></div>

{% endblock %}

cart/templates/cart/list_sabad.html
{% extends "base.html" %}

{% load humanize %}
{% block titel %}  سبد خرید    {%  endblock%}

{% block header %}   

   {% include "customer/header.html" %}
 
{% endblock%}  


{% block content %} 
 

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3"> سبد خرید </h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0"> سبد خرید</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>نام محصول </th>
                            <th>قیمت</th>
                            <th>تعداد</th>
                            <th>مجموع</th>
                            <th>حذف</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in cart %}                        
                        <tr>
                            <td class="align-middle"><img src="{{item.product.picture.url}}" alt="" style="width: 50px;"> {{item.product.name}}</td>
                            <td class="align-middle">{{item.product.takhfif|intcomma}} <span>تومان</span></td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <a  href = "{% url 'cart:reduce_number_from_cart' item.product.pk %}" class="btn btn-sm btn-primary" >
                                        <i class="fa fa-minus"></i>
                                        </a>
                                    </div>
                                    <input type="text" class="form-control form-control-sm bg-secondary text-center" value="{{item.quantity}}">
                                    <div class="input-group-btn">
                                        <a href = "{% url 'cart:add_to_cart'  item.product.pk %}" class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">{{item.total_price}}</td>
                            <td class="align-middle">
                                <a href="{% url 'cart:remove_from_cart' item.product.pk %}">

                                  <button class="btn btn-sm btn-primary"> 
                                
                                  <i class="fa fa-times"></i>
                                </a>  
                              
                            </button tar></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
             {% if takhfif == 0   %}
                  <form class="mb-5" action="{% url 'cart:codeTakhfif' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name = 'code' class="form-control p-4" placeholder="کد تخفیف">
                        <div class="input-group-append">
                         <button type = 'submit'  value = ' اعمال کد تخفیف' class="btn btn-primary">کد تخفیف را اعمال کنید    </button>                
                        </div>
                      </form>
                    </div>
                </form>

             {% else %}
             <a href = "{% url 'cart:delet_takhfif' %}"> 
              <button type = 'submit'  value = ' اعمال کد تخفیف' class="btn btn-primary">  کد تخفیف اعمال شده را حذف کنید    </button>                
             {% endif %}   
                
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0"> جمع سبد </h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6  class="font-weight-medium"> جمع مبلغ</h6>
                            <h6  class="font-weight-medium"> <span> تومان </span><span id="subtotal"> {{alljame|intcomma}}   </span> </h6>
                        </div>

                        <div class="d-flex justify-content-between">
                            <h6  class="font-weight-medium"> تخفیف  </h6>
                            <h6  class="font-weight-medium"> <span> تومان </span> <span id="takhfif" >{{takhfif|intcomma}} </span></h6>
                        </div>
                            

                        <div class="d-flex justify-content-between">
                            <h6  class="font-weight-medium">هزینه حمل و نقل</h6>
                            <h6  class="font-weight-medium"> <span> تومان </span> <span id="shipping" >{{hamlonaghl|intcomma}} </span></h6>
                        </div>

                        
                    </div>


                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold"> جمع کل </h5>
                            <h5  id="jam" class="font-weight-bold">{{kol}}</h5>
                        </div>
                         <a href="{% url 'shopindex' %}">
                            <button  class="btn btn-block btn-primary my-3 py-3">ادامه خرید</button>
                         </a>
                         <form action ="{% url 'pardakht' %}  " method = 'POST'>
                            {% csrf_token %}
                             <button name= 'mablagh' type = "submit" value = "{{kol}}" class="btn btn-block btn-primary my-3 py-3"> تکمیل خرید  </button>
                         </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

  
{% endblock %} 


{% block footer%}   
   {% include  "customer/footer.html" %}
{% endblock%}  
0