bazbia/urls.py
from django.contrib import admin
from django.urls import path ,include
from shop import views 
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.list_product  , name = 'index' ),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('customer/', include('customer.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls'))

]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('reducenumber/<product_id>' , views.reduce_number_from_cart , name = 'reduce_number_from_cart'),
    path('list/', views.show_cart, name='show_cart'),
    path('codeTkhfif/',views.codeTakhfif , name='codeTakhfif'),
    path('deletTkhfif/',views.deletTakhfif , name='delet_takhfif'),

]

shop/urls.py
from django.urls import path 
from shop import views 
urlpatterns = [
    path('', views.list_product  , name = 'shopindex' ),
    path('listproduct/',views.list_product , name= 'list_product')
]

shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



class Category(models.Model) : 
   name =   models.CharField(max_length=50)
   sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
   is_sub = models.BooleanField(default=False)    # اگر درست بودن زیر مجموع دارد


   def __str__(self):
       return self.name    

class Daste(models.Model):
    name= models.CharField(max_length=50)
    enghlishNmae = models.CharField(max_length=50 ,null=True, blank=True )
    picture = models.ImageField(upload_to='upload/dasteh' ,default='upload/dasteh/defult.jpg')
    type = models.CharField(max_length=50 ,null=True , blank=True)   
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=500,default='',blank=True,null=True)
    price = models.BigIntegerField(default=0)
    takhfif = models.BigIntegerField(default=0)
    picture = models.ImageField(upload_to='upload/product')
    category = models.ForeignKey("Category", on_delete=models.CASCADE , null=True) 
    slug = models.SlugField(unique = True)
    dasteh = models.ManyToManyField(Daste, related_name='dasteh_name')
    
    def __str__(self):
        return self.name

   

class Moshabe (models.Model) : 
     productOne = models.ForeignKey(Product , on_delete=models.DO_NOTHING ,related_name='poduct2product' , null=True) 
     productTWO = models.ForeignKey(Product , on_delete=models.DO_NOTHING  , related_name="kalayeMoshabeh" , null=True) 

     def __str__(self):
        return self.productOne.name + ' with ' + self.productTWO.name  

class Slide(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='upload/slidepic')
    disSmall = models.TextField()
    disBig = models.TextField()
    state = models.CharField( max_length=10, default='' , null=True , blank=True)

    def __str__(self):
        return self.name

class Collection(models.Model):
    name = models.CharField(max_length=50)
    enName = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='upload/collection')

shop/views.py
from django.shortcuts import render , redirect
from shop.models import Category,Slide,Daste,Collection,Product
from customer.models  import Faktor, ProductFaktor , ListState
from account.views import accesspage
from config.baseClass import DasteBytedad , productByData 
from cart.utils.cart import Cart

def list_product(request):
 
  

  catlist =  Category.objects.all()
  list_slide = Slide.objects.all()
  list_dasteh = Daste.objects.all()
  list_colection = Collection.objects.all()
  

  
##############3 LIST DASTEH 
  listdastehbytedad = []   
  for l in list_dasteh:
     ld = DasteBytedad(l,len(Product.objects.filter(dasteh = l)))
     listdastehbytedad.append(ld)




#####################3 LIST PRODUCT
  try:
   if (request.GET['daste']):
     dasteh = Daste.objects.get(enghlishNmae=request.GET['daste'])
     if dasteh:
      list_product = Product.objects.filter(dasteh = dasteh)
      nameDasteh = dasteh.name
  except:    
     list_product = Product.objects.all() 
     nameDasteh = 'جدید ترین محصولات'
    
    
#######  شمارش تعداد محصولات داخل سبد خرید 
  cart = Cart(request)     
  tedadSaba =  len(cart.cart)
  
  context= {
        'catlist'      : catlist,
        'listslid'     : list_slide,
        'listDasteh'   : listdastehbytedad,
        'listcolection': list_colection , 
        'listpruduct'  : list_product,
        'namedasteh'   : nameDasteh    ,
        'tedadSabad'   : tedadSaba   ## تعداد محصولات داخل سبد خرید  
      }

  return render(request , 'shop/list_product.html' ,context) 
  

shop/templates/shop/header/featured.html
  <!-- Featured Start -->
  <div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0"> تضمین کیفیت</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0"> ارسال رایگان</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">ضمانت بازگشت </h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">پشتیبانی 24ساعته </h5>
            </div>
        </div>
    </div>

shop/templates/shop/header/header.html
{% load static %} {% include "messages.html" %}

<div class="container-fluid">
  <div class="row bg-secondary py-2 px-xl-5">
    <div class="col-lg-6 d-none d-lg-block">
      <div class="d-inline-flex align-items-center">
        <a class="text-dark" href="">FAQs</a>
        <span class="text-muted px-2">|</span>
        <a class="text-dark" href="">Help</a>
        <span class="text-muted px-2">|</span>
        <a class="text-dark" href="">Support</a>
      </div>
    </div>
    <div class="col-lg-6 text-center text-lg-right">
      <div class="d-inline-flex align-items-center">
        <a class="text-dark px-2" href="">
          <i class="fab fa-telegram"></i>
        </a>
        <a class="text-dark px-2" href="">
          <i class="fab fa-linkedin-in"></i>
        </a>
        <a class="text-dark px-2" href="">
          <i class="fab fa-instagram"></i>
        </a>
        <a class="text-dark pl-2" href="">
          <i class="fab fa-youtube"></i>
        </a>
      </div>
    </div>
  </div>
  <div class="row align-items-center py-3 px-xl-5">
    <div class="col-lg-3 d-none d-lg-block">
      <a href="" class="text-decoration-none">
        <h1 class="m-0 display-5 font-weight-semi-bold">
          <span class="text-primary font-weight-bold border px-3 mr-1">B</span
          >بازبیا
        </h1>
      </a>
    </div>
    <div class="col-lg-6 col-6 text-left">
      <form action="">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="جستجوی کنید" />
          <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
              <i class="fa fa-search"></i>
            </span>
          </div>
        </div>
      </form>
    </div>
    <div class="col-lg-3 col-6 text-right">
      <a href="" class="btn border">
        <i class="fas fa-heart text-primary"></i>
        <span class="badge">0</span>
      </a>
      <a
        href="{% url 'cart:show_cart' %}"
        class="btn border"
      >
        <i class="fas fa-shopping-cart text-primary"></i>
        <span class="badge">{{tedadSabad}}</span>
      </a>
    </div>
  </div>
</div>

<!-- Navbar Start -->
<div class="container-fluid mb-5">
  <div class="row border-top px-xl-5">
    <div class="col-lg-3 d-none d-lg-block">
      <a
        class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100"
        data-toggle="collapse"
        href="#navbar-vertical"
        style="height: 65px; margin-top: -1px; padding: 0 30px"
      >
        <h6 class="m-0">دسته بندی محصولات</h6>
        <i class="fa fa-angle-down text-dark"></i>
      </a>
      <nav
        class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0"
        id="navbar-vertical"
      >
        <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
          {% for cat in catlist %}     <!--  لایه اول دسته محصولات -->
            <!-- check if category is parent -->
            {% if  not cat.is_sub %}     
             <!-- parent--> 
              <div class="nav-item dropdown">
               <a href="#" class="nav-link" data-toggle="dropdown">
                {{cat.name}} <i class="fa fa-angle-down float-right mt-1"></i>
               </a>
               <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                {% for cat_1 in  cat.sub_categories.all %}      <!--  لایه دوم دسته محصولات -->
                   <a href="#" class="nav-link" data-toggle="dropdown">
                   {{cat_1.name}} <i class="fa fa-angle-down float-right mt-1"></i>
                   </a>
                   <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                   {% for cat_2 in cat_1.sub_categories.all%}    <!--  لایه سوم دسته محصولات -->
                    <a href="" class="nav-item nav-link">{{cat_2.name}}</a>
                   {% endfor %} 
                  </div> 
                {% endfor %} 
                
               </div>
              </div> 
            {% endif %}

          {% endfor %}
 
        </div>
      </nav>
    </div>

    <div class="col-lg-9">
      <nav
        class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0"
      >
        <a href="" class="text-decoration-none d-block d-lg-none">
          <h1 class="m-0 display-5 font-weight-semi-bold">
            <span class="text-primary font-weight-bold border px-3 mr-1">E</span
            >بازبیا
          </h1>
        </a>
        <button
          type="button"
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-between"
          id="navbarCollapse"
        >
          <div class="navbar-nav mr-auto py-0">
            <a href="{% url 'list_product' %}" class="nav-item nav-link active">خانه</a>
            <a href="{% url 'list_product' %}" class="nav-item nav-link"
              >فروشگاه</a
            >
            <a href="detail.html" class="nav-item nav-link"> جزيیات</a>
            <div class="nav-item dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                >صفحات</a
              >
              <div class="dropdown-menu rounded-0 m-0">
                <a
                  href="{% url 'cart:show_cart' %}"
                  class="dropdown-item"
                >
                  سبد خرید</a
                >
                <a href="checkout.html" class="dropdown-item">بررسی</a>
              </div>
            </div>
            <a href="contact.html" class="nav-item nav-link">ارتباط با ما</a>
          </div>
          {% if request.user.is_authenticated %}
          <div class="navbar-nav ml-auto py-0">
            <a href="" class="nav-item nav-link"> خروج </a>
          </div>
          {% else %}
          <div class="navbar-nav ml-auto py-0">
            <a href="" class="nav-item nav-link">ورود</a>
            <a href="" class="nav-item nav-link">ثبت نام </a>
          </div>
          {% endif %}
        </div>
      </nav>

      {% include "headers/mainheader/slider.html" %}
    </div>
  </div>
</div>
<!-- Navbar End -->

shop/templates/shop/header/slider.html
<!-- slide start -->
<div id="header-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        {% for slide in listslid %}                    
        <div class="carousel-item {{slide.state}}" style="height: 410px;">
            <img class="img-fluid" src="{{slide.picture.url}}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="p-3" style="max-width: 700px;">
                    <h4 class="text-light text-uppercase font-weight-medium mb-3">{{slide.disBig}}</h4>
                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">{{slide.disSmall}}</h3>
                    <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
        <div class="btn btn-dark" style="width: 45px; height: 45px;">
            <span class="carousel-control-prev-icon mb-n2"></span>
        </div>
    </a>
    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
        <div class="btn btn-dark" style="width: 45px; height: 45px;">
            <span class="carousel-control-next-icon mb-n2"></span>
        </div>
    </a>
</div>
<!-- slide end -->